name: Weekly Auto Predictions

on:
  schedule:
    - cron: "0 8 * * FRI"   # every Friday at 08:00 UTC (change to match your league schedule)
  workflow_dispatch:        # allows manual run from GitHub UI

jobs:
  run-predictions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run auto predictions
        run: |
          python app.py

      - name: Commit predictions
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add upcoming_predictions.csv
          git commit -m "Auto-update predictions for upcoming fixtures"
          git push
