name: Retrain Model

on:
  schedule:
    - cron: '50 8 * * 3'  # Runs every Wednesday at 8:30 AM UTC

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib

    - name: Retrain model
      run: |
        python auto_model_retrainer.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Retrain model" || echo "No changes to commit"
        git push
