name: Update PL Matches

on:
  schedule:
    - cron: '30 09 * * 2'  
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify a compatible Python version (e.g., 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch latest changes
      run: |
        git fetch origin

    - name: Rebase branch
      run: |
        git rebase origin/main

    - name: Run script
      run: python auto_update_match_df.py

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automated update"

    - name: Fetch latest changes before pushing
      run: |
        git fetch origin

    - name: Rebase branch before pushing
      run: |
        git rebase origin/main

    - name: Push changes
      run: |
        git push
