name: Reconfigure Features

on:
  schedule:
    - cron: '20 12 * * 3'  # Runs every Wednesday at 8:30 AM UTC

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn joblib

    - name: Fetch latest changes
      run: |
        git fetch origin

    - name: Rebase branch
      run: |
        git rebase origin/main

    - name: Run script
      run: python team_features.py

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automated update"

    - name: Fetch latest changes before pushing
      run: |
        git fetch origin

    - name: Rebase branch before pushing
      run: |
        git rebase origin/main

    - name: Push changes
      run: |
        git push
