name: Update PL Matches
on:
  schedule:
    - cron: '30 09 * * 2'
  workflow_dispatch:

permissions:
  contents: write

env:
  TARGET_BRANCH: auto/pl-matches   # <-- set it here

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, ref: main }

      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt
      - run: python auto_update_match_df.py

      - id: commit
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Automated update (PL matches)"
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Push to target branch (create if missing)
        if: steps.commit.outputs.changed == 'true'
        env:
          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Target branch: ${TARGET_BRANCH}"
          git check-ref-format --branch "${TARGET_BRANCH}"
          git checkout -B "${TARGET_BRANCH}"
          git push -u origin "${TARGET_BRANCH}" --force-with-lease
