name: Update PL Matches

on:
  schedule:
    - cron: '30 09 * * 2'  
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify a compatible Python version (e.g., 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch latest changes
      run: |
        git fetch origin

    - name: Rebase branch
      run: |
        git rebase origin/main

    - name: Run script
      run: python auto_update_match_df.py

    - name: Commit changes (if any) with GitHub Actions identity
      id: commit
      run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Automated update (PL matches)"
          echo "changed=true" >> $GITHUB_OUTPUT

    - name: Push to target branch (create if missing)
      if: steps.commit.outputs.changed == 'true'
      env:
          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
      run: |
          git checkout -B "$TARGET_BRANCH"              # create/reset local branch at current HEAD
          git push -u origin "$TARGET_BRANCH" --force-with-lease
